# Generated by Django 4.2.2 on 2023-06-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_roles', models.CharField(choices=[('FRONTEND DEVELOPER', 'FRONTEND DEVELOPER'), ('BACKEND DEVELOPER', 'BACKEND DEVELOPER'), ('PRODUCT DESIGNER', 'PRODUCT DESIGNER'), ('ML ENGINEER INTERN', 'ML ENGINEER INTERN'), ('DIGITAL MARKETING INTERN', 'DIGITAL MARKETING INTERN')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('resume_link', models.URLField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.role')),
            ],
        ),
    ]
