# Generated by Django 4.2.2 on 2023-06-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='last_name',
        ),
        migrations.AddField(
            model_name='applicants',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicants',
            name='full_name',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
